---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-ricktech-io-v1alpha1-flipper
  failurePolicy: Fail
  name: mflipper.kb.io
  rules:
  - apiGroups:
    - crd.ricktech.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flippers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-ricktech-io-v1alpha1-flipper
  failurePolicy: Fail
  name: vflipper.kb.io
  rules:
  - apiGroups:
    - crd.ricktech.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flippers
  sideEffects: None
