# permissions for end users to view flippers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: flipper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: autorollout-operator
    app.kubernetes.io/part-of: autorollout-operator
    app.kubernetes.io/managed-by: kustomize
  name: flipper-viewer-role
rules:
- apiGroups:
  - crd.ricktech.io
  resources:
  - flippers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.ricktech.io
  resources:
  - flippers/status
  verbs:
  - get
